<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>kairo_ui</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="bootstrap" Version="5.3.8" />
    <PackageReference Include="font-awesome" Version="4.7.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.1" />
    <PackageReference Include="Serilog.Sinks.Console" Version="5.0.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\Dashboard\" />
    <Folder Include="Views\Dashboard\" />
    <Folder Include="wwwroot\js\constants\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CBS.COMMON\CBS.Entities.Common.csproj" />
    <ProjectReference Include="..\CBS.Entities.SystemCore\CBS.Entities.SystemCore.csproj" />
  </ItemGroup>

</Project>
