<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>kairo_ui</RootNamespace>
    <!-- Disable Hot Reload to prevent crash when opening file dialogs -->
    <StartupHotReload>false</StartupHotReload>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\js\auth\**" />
    <Compile Remove="wwwroot\js\pages\**" />
    <Content Remove="wwwroot\js\auth\**" />
    <Content Remove="wwwroot\js\pages\**" />
    <EmbeddedResource Remove="wwwroot\js\auth\**" />
    <EmbeddedResource Remove="wwwroot\js\pages\**" />
    <None Remove="wwwroot\js\auth\**" />
    <None Remove="wwwroot\js\pages\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="bootstrap" Version="5.3.8" />
    <PackageReference Include="font-awesome" Version="4.7.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.1" />
    <PackageReference Include="Serilog.Sinks.Console" Version="5.0.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
    <PackageReference Include="StackExchange.Redis" Version="2.11.8" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\Dashboard\" />
    <Folder Include="Views\Dashboard\" />
    <Folder Include="wwwroot\js\constants\" />
    <Folder Include="wwwroot\js\utils\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CBS.COMMON\CBS.Entities.Common.csproj" />
    <ProjectReference Include="..\CBS.Entities.SystemCore\CBS.Entities.SystemCore.csproj" />
  </ItemGroup>

</Project>
